// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Hpd1NnRiALDpK_TOmrwZXR9oqpUgIbU',
    appId: '1:364019373598:web:8a8b8fd4db6328a9b9800f',
    messagingSenderId: '364019373598',
    projectId: 'reemoapp-1',
    authDomain: 'reemoapp-1.firebaseapp.com',
    storageBucket: 'reemoapp-1.firebasestorage.app',
    measurementId: 'G-S0H37PFE4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeJKNleOxvHkPprp3FCX-nIb7vxOcRgE',
    appId: '1:364019373598:android:bba1c7af35220ba5b9800f',
    messagingSenderId: '364019373598',
    projectId: 'reemoapp-1',
    storageBucket: 'reemoapp-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSCNP2dM7vNNPFSnga8-cm-PbJsX6c02A',
    appId: '1:364019373598:ios:e18dfee6dde9f05bb9800f',
    messagingSenderId: '364019373598',
    projectId: 'reemoapp-1',
    storageBucket: 'reemoapp-1.firebasestorage.app',
    iosBundleId: 'com.example.appReem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSCNP2dM7vNNPFSnga8-cm-PbJsX6c02A',
    appId: '1:364019373598:ios:e18dfee6dde9f05bb9800f',
    messagingSenderId: '364019373598',
    projectId: 'reemoapp-1',
    storageBucket: 'reemoapp-1.firebasestorage.app',
    iosBundleId: 'com.example.appReem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Hpd1NnRiALDpK_TOmrwZXR9oqpUgIbU',
    appId: '1:364019373598:web:ddf6a1241b9fc3d2b9800f',
    messagingSenderId: '364019373598',
    projectId: 'reemoapp-1',
    authDomain: 'reemoapp-1.firebaseapp.com',
    storageBucket: 'reemoapp-1.firebasestorage.app',
    measurementId: 'G-7QFVDEKK23',
  );
}
